// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: spec/kgi/v1alpha1/gate.proto

package kgiv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatePhase int32

const (
	GatePhase_GATE_PHASE_UNSPECIFIED  GatePhase = 0
	GatePhase_GATE_PHASE_PASSED       GatePhase = 1
	GatePhase_GATE_PHASE_FAILED       GatePhase = 2
	GatePhase_GATE_PHASE_RUNNING      GatePhase = 3
	GatePhase_GATE_PHASE_INCONCLUSIVE GatePhase = 4
)

// Enum value maps for GatePhase.
var (
	GatePhase_name = map[int32]string{
		0: "GATE_PHASE_UNSPECIFIED",
		1: "GATE_PHASE_PASSED",
		2: "GATE_PHASE_FAILED",
		3: "GATE_PHASE_RUNNING",
		4: "GATE_PHASE_INCONCLUSIVE",
	}
	GatePhase_value = map[string]int32{
		"GATE_PHASE_UNSPECIFIED":  0,
		"GATE_PHASE_PASSED":       1,
		"GATE_PHASE_FAILED":       2,
		"GATE_PHASE_RUNNING":      3,
		"GATE_PHASE_INCONCLUSIVE": 4,
	}
)

func (x GatePhase) Enum() *GatePhase {
	p := new(GatePhase)
	*p = x
	return p
}

func (x GatePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GatePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_kgi_v1alpha1_gate_proto_enumTypes[0].Descriptor()
}

func (GatePhase) Type() protoreflect.EnumType {
	return &file_spec_kgi_v1alpha1_gate_proto_enumTypes[0]
}

func (x GatePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GatePhase.Descriptor instead.
func (GatePhase) EnumDescriptor() ([]byte, []int) {
	return file_spec_kgi_v1alpha1_gate_proto_rawDescGZIP(), []int{0}
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       string                 `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Pipeline      string                 `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Stage         string                 `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Gate          string                 `protobuf:"bytes,6,opt,name=gate,proto3" json:"gate,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,7,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_spec_kgi_v1alpha1_gate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kgi_v1alpha1_gate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_spec_kgi_v1alpha1_gate_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *EvaluateRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *EvaluateRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *EvaluateRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *EvaluateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EvaluateRequest) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *EvaluateRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         GatePhase              `protobuf:"varint,1,opt,name=phase,proto3,enum=kapro.kgi.v1alpha1.GatePhase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_spec_kgi_v1alpha1_gate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kgi_v1alpha1_gate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_spec_kgi_v1alpha1_gate_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateResponse) GetPhase() GatePhase {
	if x != nil {
		return x.Phase
	}
	return GatePhase_GATE_PHASE_UNSPECIFIED
}

func (x *EvaluateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_spec_kgi_v1alpha1_gate_proto protoreflect.FileDescriptor

const file_spec_kgi_v1alpha1_gate_proto_rawDesc = "" +
	"\n" +
	"\x1cspec/kgi/v1alpha1/gate.proto\x12\x12kapro.kgi.v1alpha1\"\xb7\x02\n" +
	"\x0fEvaluateRequest\x12\x18\n" +
	"\arelease\x18\x01 \x01(\tR\arelease\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1a\n" +
	"\bpipeline\x18\x03 \x01(\tR\bpipeline\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x12\n" +
	"\x04gate\x18\x06 \x01(\tR\x04gate\x12S\n" +
	"\n" +
	"parameters\x18\a \x03(\v23.kapro.kgi.v1alpha1.EvaluateRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x10EvaluateResponse\x123\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1d.kapro.kgi.v1alpha1.GatePhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x8a\x01\n" +
	"\tGatePhase\x12\x1a\n" +
	"\x16GATE_PHASE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11GATE_PHASE_PASSED\x10\x01\x12\x15\n" +
	"\x11GATE_PHASE_FAILED\x10\x02\x12\x16\n" +
	"\x12GATE_PHASE_RUNNING\x10\x03\x12\x1b\n" +
	"\x17GATE_PHASE_INCONCLUSIVE\x10\x042d\n" +
	"\vGateService\x12U\n" +
	"\bEvaluate\x12#.kapro.kgi.v1alpha1.EvaluateRequest\x1a$.kapro.kgi.v1alpha1.EvaluateResponseB.Z,kapro.io/kapro/spec/kgi/v1alpha1;kgiv1alpha1b\x06proto3"

var (
	file_spec_kgi_v1alpha1_gate_proto_rawDescOnce sync.Once
	file_spec_kgi_v1alpha1_gate_proto_rawDescData []byte
)

func file_spec_kgi_v1alpha1_gate_proto_rawDescGZIP() []byte {
	file_spec_kgi_v1alpha1_gate_proto_rawDescOnce.Do(func() {
		file_spec_kgi_v1alpha1_gate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_kgi_v1alpha1_gate_proto_rawDesc), len(file_spec_kgi_v1alpha1_gate_proto_rawDesc)))
	})
	return file_spec_kgi_v1alpha1_gate_proto_rawDescData
}

var file_spec_kgi_v1alpha1_gate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spec_kgi_v1alpha1_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spec_kgi_v1alpha1_gate_proto_goTypes = []any{
	(GatePhase)(0),           // 0: kapro.kgi.v1alpha1.GatePhase
	(*EvaluateRequest)(nil),  // 1: kapro.kgi.v1alpha1.EvaluateRequest
	(*EvaluateResponse)(nil), // 2: kapro.kgi.v1alpha1.EvaluateResponse
	nil,                      // 3: kapro.kgi.v1alpha1.EvaluateRequest.ParametersEntry
}
var file_spec_kgi_v1alpha1_gate_proto_depIdxs = []int32{
	3, // 0: kapro.kgi.v1alpha1.EvaluateRequest.parameters:type_name -> kapro.kgi.v1alpha1.EvaluateRequest.ParametersEntry
	0, // 1: kapro.kgi.v1alpha1.EvaluateResponse.phase:type_name -> kapro.kgi.v1alpha1.GatePhase
	1, // 2: kapro.kgi.v1alpha1.GateService.Evaluate:input_type -> kapro.kgi.v1alpha1.EvaluateRequest
	2, // 3: kapro.kgi.v1alpha1.GateService.Evaluate:output_type -> kapro.kgi.v1alpha1.EvaluateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spec_kgi_v1alpha1_gate_proto_init() }
func file_spec_kgi_v1alpha1_gate_proto_init() {
	if File_spec_kgi_v1alpha1_gate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_kgi_v1alpha1_gate_proto_rawDesc), len(file_spec_kgi_v1alpha1_gate_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spec_kgi_v1alpha1_gate_proto_goTypes,
		DependencyIndexes: file_spec_kgi_v1alpha1_gate_proto_depIdxs,
		EnumInfos:         file_spec_kgi_v1alpha1_gate_proto_enumTypes,
		MessageInfos:      file_spec_kgi_v1alpha1_gate_proto_msgTypes,
	}.Build()
	File_spec_kgi_v1alpha1_gate_proto = out.File
	file_spec_kgi_v1alpha1_gate_proto_goTypes = nil
	file_spec_kgi_v1alpha1_gate_proto_depIdxs = nil
}
