kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: runtime.kapro.io
        version: v1alpha1
        kind: PromotionRun
      metricNamePrefix: kapro_promotionrun
      labelsFromPath:
        promotionrun: [metadata, name]
      metrics:
        - name: created
          help: Kapro PromotionRun creation timestamp.
          each:
            type: Gauge
            gauge:
              path: [metadata, creationTimestamp]
        - name: status_phase
          help: Kapro PromotionRun phase.
          each:
            type: StateSet
            stateSet:
              labelName: phase
              path: [status, phase]
              list: [Pending, Progressing, Complete, Failed]
        - name: status_condition
          help: Kapro PromotionRun status condition.
          each:
            type: Gauge
            gauge:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                reason: [reason]
              valueFrom: [status]
    - groupVersionKind:
        group: kapro.io
        version: v1alpha1
        kind: Trigger
      metricNamePrefix: kapro_trigger
      labelsFromPath:
        trigger: [metadata, name]
      metrics:
        - name: status_active_promotionrun_count
          help: Number of active non-terminal PromotionRuns tracked by a Kapro Trigger.
          each:
            type: Gauge
            gauge:
              path: [status, activePromotionRunCount]
        - name: status_condition
          help: Kapro Trigger status condition.
          each:
            type: Gauge
            gauge:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                reason: [reason]
              valueFrom: [status]
    - groupVersionKind:
        group: kapro.io
        version: v1alpha1
        kind: Plugin
      metricNamePrefix: kapro_plugin
      labelsFromPath:
        plugin: [metadata, name]
        plugin_type: [spec, type]
        plugin_name: [spec, name]
      metrics:
        - name: status_ready
          help: Kapro Plugin ready status.
          each:
            type: Gauge
            gauge:
              path: [status, ready]
        - name: status_condition
          help: Kapro Plugin status condition.
          each:
            type: Gauge
            gauge:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                reason: [reason]
              valueFrom: [status]
