apiVersion: kapro.io/v1alpha1
kind: FleetCluster
metadata:
  name: checkout-canary
  labels:
    kapro.io/tier: canary
    kapro.io/region: eu
spec:
  delivery:
    mode: push
    backendRef: flux
    parameters:
      resourceSet: checkout-demo
      namespace: flux-system
      inputField: tag
      tenantField: tenant
---
apiVersion: kapro.io/v1alpha1
kind: FleetCluster
metadata:
  name: checkout-prod-eu
  labels:
    kapro.io/tier: production
    kapro.io/region: eu
spec:
  delivery:
    mode: push
    backendRef: flux
    parameters:
      resourceSet: checkout-demo
      namespace: flux-system
      inputField: tag
      tenantField: tenant
---
apiVersion: kapro.io/v1alpha1
kind: FleetCluster
metadata:
  name: checkout-prod-us
  labels:
    kapro.io/tier: production
    kapro.io/region: us
spec:
  delivery:
    mode: push
    backendRef: flux
    parameters:
      resourceSet: checkout-demo
      namespace: flux-system
      inputField: tag
      tenantField: tenant
