{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kapro-cluster-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kapro-cluster-controller.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kapro-cluster-controller.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
{{- end }}
