apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapro-cluster-controller
rules:
- apiGroups: ["kapro.io"]
  resources: ["memberclusters", "memberclusters/status"]
  verbs: ["get", "list", "patch", "update", "watch"]
