---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapro-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/kube-apiserver-client
  resources:
  - signers
  verbs:
  - approve
- apiGroups:
  - kapro.io
  resources:
  - approvals
  - releasereports
  - releases
  - syncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - artifacts
  - gatepolicies
  - gatetemplates
  - pipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - bootstraptokens
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - bootstraptokens/finalizers
  - managedclusters/finalizers
  - releases/finalizers
  - syncs/finalizers
  verbs:
  - update
- apiGroups:
  - kapro.io
  resources:
  - bootstraptokens/status
  verbs:
  - patch
  - update
- apiGroups:
  - kapro.io
  resources:
  - environments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - environments/status
  - managedclusters/status
  - pipelines/status
  - releasereports/status
  - releases/status
  - syncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kapro.io
  resources:
  - managedclusters
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
