---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapro-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - applicationsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - resourcesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - agentpolicies
  - backendprofiles
  - promotionpolicies
  - promotionsources
  - promotiontriggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - agentpolicies/status
  - approvals/status
  - backendprofiles/status
  - fleetclusters/status
  - kaproes/status
  - pluginregistrations/status
  - promotionpolicies/status
  - promotionruns/status
  - promotions/status
  - promotiontargets/status
  - promotiontriggers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kapro.io
  resources:
  - approvals
  - fleetclusters
  - kaproes
  - promotionplans
  - promotionruns
  - promotions
  - promotiontargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - pluginregistrations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - promotionruns/finalizers
  - promotions/finalizers
  verbs:
  - update
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - gitrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - watch
