---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapro-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - kapro.io
  resources:
  - approvals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - batchruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - batchruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kapro.io
  resources:
  - bootstraptokens
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - bootstraptokens/finalizers
  verbs:
  - update
- apiGroups:
  - kapro.io
  resources:
  - bootstraptokens/status
  verbs:
  - patch
  - update
- apiGroups:
  - kapro.io
  resources:
  - clusterregistrations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - artifacts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - environments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - gatetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - kagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - kagents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kapro.io
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kapro.io
  resources:
  - progressionpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - promotionpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - promotions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - promotions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kapro.io
  resources:
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - releases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
