// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: spec/kpi/v1alpha1/planner.proto

package kpiv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanningDecision int32

const (
	PlanningDecision_PLANNING_DECISION_UNSPECIFIED PlanningDecision = 0
	PlanningDecision_PLANNING_DECISION_INCLUDE     PlanningDecision = 1
	PlanningDecision_PLANNING_DECISION_SKIP        PlanningDecision = 2
	PlanningDecision_PLANNING_DECISION_DEFER       PlanningDecision = 3
)

// Enum value maps for PlanningDecision.
var (
	PlanningDecision_name = map[int32]string{
		0: "PLANNING_DECISION_UNSPECIFIED",
		1: "PLANNING_DECISION_INCLUDE",
		2: "PLANNING_DECISION_SKIP",
		3: "PLANNING_DECISION_DEFER",
	}
	PlanningDecision_value = map[string]int32{
		"PLANNING_DECISION_UNSPECIFIED": 0,
		"PLANNING_DECISION_INCLUDE":     1,
		"PLANNING_DECISION_SKIP":        2,
		"PLANNING_DECISION_DEFER":       3,
	}
)

func (x PlanningDecision) Enum() *PlanningDecision {
	p := new(PlanningDecision)
	*p = x
	return p
}

func (x PlanningDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanningDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_kpi_v1alpha1_planner_proto_enumTypes[0].Descriptor()
}

func (PlanningDecision) Type() protoreflect.EnumType {
	return &file_spec_kpi_v1alpha1_planner_proto_enumTypes[0]
}

func (x PlanningDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanningDecision.Descriptor instead.
func (PlanningDecision) EnumDescriptor() ([]byte, []int) {
	return file_spec_kpi_v1alpha1_planner_proto_rawDescGZIP(), []int{0}
}

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_spec_kpi_v1alpha1_planner_proto_rawDescGZIP(), []int{0}
}

type GetCapabilitiesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractVersion string                 `protobuf:"bytes,1,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	PluginVersion   string                 `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_spec_kpi_v1alpha1_planner_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapabilitiesResponse) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type PlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       string                 `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Pipeline      string                 `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Strategy      *StageStrategy         `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Targets       []*Target              `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,7,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_spec_kpi_v1alpha1_planner_proto_rawDescGZIP(), []int{2}
}

func (x *PlanRequest) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *PlanRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *PlanRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *PlanRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PlanRequest) GetStrategy() *StageStrategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *PlanRequest) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *PlanRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type StageStrategy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxParallel    int32                  `protobuf:"varint,1,opt,name=max_parallel,json=maxParallel,proto3" json:"max_parallel,omitempty"`
	MaxUnavailable int32                  `protobuf:"varint,2,opt,name=max_unavailable,json=maxUnavailable,proto3" json:"max_unavailable,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StageStrategy) Reset() {
	*x = StageStrategy{}
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageStrategy) ProtoMessage() {}

func (x *StageStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageStrategy.ProtoReflect.Descriptor instead.
func (*StageStrategy) Descriptor() ([]byte, []int) {
	return file_spec_kpi_v1alpha1_planner_proto_rawDescGZIP(), []int{3}
}

func (x *StageStrategy) GetMaxParallel() int32 {
	if x != nil {
		return x.MaxParallel
	}
	return 0
}

func (x *StageStrategy) GetMaxUnavailable() int32 {
	if x != nil {
		return x.MaxUnavailable
	}
	return 0
}

type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	ActiveRelease string                 `protobuf:"bytes,4,opt,name=active_release,json=activeRelease,proto3" json:"active_release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_spec_kpi_v1alpha1_planner_proto_rawDescGZIP(), []int{4}
}

func (x *Target) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Target) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Target) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Target) GetActiveRelease() string {
	if x != nil {
		return x.ActiveRelease
	}
	return ""
}

type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*PlannedTarget       `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_spec_kpi_v1alpha1_planner_proto_rawDescGZIP(), []int{5}
}

func (x *PlanResponse) GetTargets() []*PlannedTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type PlannedTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Decision      PlanningDecision       `protobuf:"varint,2,opt,name=decision,proto3,enum=kapro.kpi.v1alpha1.PlanningDecision" json:"decision,omitempty"`
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlannedTarget) Reset() {
	*x = PlannedTarget{}
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlannedTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlannedTarget) ProtoMessage() {}

func (x *PlannedTarget) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kpi_v1alpha1_planner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlannedTarget.ProtoReflect.Descriptor instead.
func (*PlannedTarget) Descriptor() ([]byte, []int) {
	return file_spec_kpi_v1alpha1_planner_proto_rawDescGZIP(), []int{6}
}

func (x *PlannedTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlannedTarget) GetDecision() PlanningDecision {
	if x != nil {
		return x.Decision
	}
	return PlanningDecision_PLANNING_DECISION_UNSPECIFIED
}

func (x *PlannedTarget) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlannedTarget) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PlannedTarget) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_spec_kpi_v1alpha1_planner_proto protoreflect.FileDescriptor

const file_spec_kpi_v1alpha1_planner_proto_rawDesc = "" +
	"\n" +
	"\x1fspec/kpi/v1alpha1/planner.proto\x12\x12kapro.kpi.v1alpha1\"\x18\n" +
	"\x16GetCapabilitiesRequest\"\x8f\x01\n" +
	"\x17GetCapabilitiesResponse\x12)\n" +
	"\x10contract_version\x18\x01 \x01(\tR\x0fcontractVersion\x12%\n" +
	"\x0eplugin_version\x18\x02 \x01(\tR\rpluginVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\xf8\x02\n" +
	"\vPlanRequest\x12\x18\n" +
	"\arelease\x18\x01 \x01(\tR\arelease\x12\x1a\n" +
	"\bpipeline\x18\x02 \x01(\tR\bpipeline\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12=\n" +
	"\bstrategy\x18\x05 \x01(\v2!.kapro.kpi.v1alpha1.StageStrategyR\bstrategy\x124\n" +
	"\atargets\x18\x06 \x03(\v2\x1a.kapro.kpi.v1alpha1.TargetR\atargets\x12O\n" +
	"\n" +
	"parameters\x18\a \x03(\v2/.kapro.kpi.v1alpha1.PlanRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\rStageStrategy\x12!\n" +
	"\fmax_parallel\x18\x01 \x01(\x05R\vmaxParallel\x12'\n" +
	"\x0fmax_unavailable\x18\x02 \x01(\x05R\x0emaxUnavailable\"\xd4\x01\n" +
	"\x06Target\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\x06labels\x18\x02 \x03(\v2&.kapro.kpi.v1alpha1.Target.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12%\n" +
	"\x0eactive_release\x18\x04 \x01(\tR\ractiveRelease\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\fPlanResponse\x12;\n" +
	"\atargets\x18\x01 \x03(\v2!.kapro.kpi.v1alpha1.PlannedTargetR\atargets\"\xad\x01\n" +
	"\rPlannedTarget\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12@\n" +
	"\bdecision\x18\x02 \x01(\x0e2$.kapro.kpi.v1alpha1.PlanningDecisionR\bdecision\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*\x8d\x01\n" +
	"\x10PlanningDecision\x12!\n" +
	"\x1dPLANNING_DECISION_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PLANNING_DECISION_INCLUDE\x10\x01\x12\x1a\n" +
	"\x16PLANNING_DECISION_SKIP\x10\x02\x12\x1b\n" +
	"\x17PLANNING_DECISION_DEFER\x10\x032\xc7\x01\n" +
	"\x0ePlannerService\x12j\n" +
	"\x0fGetCapabilities\x12*.kapro.kpi.v1alpha1.GetCapabilitiesRequest\x1a+.kapro.kpi.v1alpha1.GetCapabilitiesResponse\x12I\n" +
	"\x04Plan\x12\x1f.kapro.kpi.v1alpha1.PlanRequest\x1a .kapro.kpi.v1alpha1.PlanResponseB.Z,kapro.io/kapro/spec/kpi/v1alpha1;kpiv1alpha1b\x06proto3"

var (
	file_spec_kpi_v1alpha1_planner_proto_rawDescOnce sync.Once
	file_spec_kpi_v1alpha1_planner_proto_rawDescData []byte
)

func file_spec_kpi_v1alpha1_planner_proto_rawDescGZIP() []byte {
	file_spec_kpi_v1alpha1_planner_proto_rawDescOnce.Do(func() {
		file_spec_kpi_v1alpha1_planner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_kpi_v1alpha1_planner_proto_rawDesc), len(file_spec_kpi_v1alpha1_planner_proto_rawDesc)))
	})
	return file_spec_kpi_v1alpha1_planner_proto_rawDescData
}

var file_spec_kpi_v1alpha1_planner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spec_kpi_v1alpha1_planner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_spec_kpi_v1alpha1_planner_proto_goTypes = []any{
	(PlanningDecision)(0),           // 0: kapro.kpi.v1alpha1.PlanningDecision
	(*GetCapabilitiesRequest)(nil),  // 1: kapro.kpi.v1alpha1.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil), // 2: kapro.kpi.v1alpha1.GetCapabilitiesResponse
	(*PlanRequest)(nil),             // 3: kapro.kpi.v1alpha1.PlanRequest
	(*StageStrategy)(nil),           // 4: kapro.kpi.v1alpha1.StageStrategy
	(*Target)(nil),                  // 5: kapro.kpi.v1alpha1.Target
	(*PlanResponse)(nil),            // 6: kapro.kpi.v1alpha1.PlanResponse
	(*PlannedTarget)(nil),           // 7: kapro.kpi.v1alpha1.PlannedTarget
	nil,                             // 8: kapro.kpi.v1alpha1.PlanRequest.ParametersEntry
	nil,                             // 9: kapro.kpi.v1alpha1.Target.LabelsEntry
}
var file_spec_kpi_v1alpha1_planner_proto_depIdxs = []int32{
	4, // 0: kapro.kpi.v1alpha1.PlanRequest.strategy:type_name -> kapro.kpi.v1alpha1.StageStrategy
	5, // 1: kapro.kpi.v1alpha1.PlanRequest.targets:type_name -> kapro.kpi.v1alpha1.Target
	8, // 2: kapro.kpi.v1alpha1.PlanRequest.parameters:type_name -> kapro.kpi.v1alpha1.PlanRequest.ParametersEntry
	9, // 3: kapro.kpi.v1alpha1.Target.labels:type_name -> kapro.kpi.v1alpha1.Target.LabelsEntry
	7, // 4: kapro.kpi.v1alpha1.PlanResponse.targets:type_name -> kapro.kpi.v1alpha1.PlannedTarget
	0, // 5: kapro.kpi.v1alpha1.PlannedTarget.decision:type_name -> kapro.kpi.v1alpha1.PlanningDecision
	1, // 6: kapro.kpi.v1alpha1.PlannerService.GetCapabilities:input_type -> kapro.kpi.v1alpha1.GetCapabilitiesRequest
	3, // 7: kapro.kpi.v1alpha1.PlannerService.Plan:input_type -> kapro.kpi.v1alpha1.PlanRequest
	2, // 8: kapro.kpi.v1alpha1.PlannerService.GetCapabilities:output_type -> kapro.kpi.v1alpha1.GetCapabilitiesResponse
	6, // 9: kapro.kpi.v1alpha1.PlannerService.Plan:output_type -> kapro.kpi.v1alpha1.PlanResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_spec_kpi_v1alpha1_planner_proto_init() }
func file_spec_kpi_v1alpha1_planner_proto_init() {
	if File_spec_kpi_v1alpha1_planner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_kpi_v1alpha1_planner_proto_rawDesc), len(file_spec_kpi_v1alpha1_planner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spec_kpi_v1alpha1_planner_proto_goTypes,
		DependencyIndexes: file_spec_kpi_v1alpha1_planner_proto_depIdxs,
		EnumInfos:         file_spec_kpi_v1alpha1_planner_proto_enumTypes,
		MessageInfos:      file_spec_kpi_v1alpha1_planner_proto_msgTypes,
	}.Build()
	File_spec_kpi_v1alpha1_planner_proto = out.File
	file_spec_kpi_v1alpha1_planner_proto_goTypes = nil
	file_spec_kpi_v1alpha1_planner_proto_depIdxs = nil
}
