// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: spec/kpi/v1alpha1/planner.proto

package kpiv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlannerService_GetCapabilities_FullMethodName = "/kapro.kpi.v1alpha1.PlannerService/GetCapabilities"
	PlannerService_Plan_FullMethodName            = "/kapro.kpi.v1alpha1.PlannerService/Plan"
)

// PlannerServiceClient is the client API for PlannerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlannerService is the Kapro Planner Interface (KPI).
//
// A planner plugin filters and orders eligible targets before Kapro binds
// ReleaseTarget objects. Kapro owns release state, retries, failure policy, and
// binding. Planner plugins only return planning decisions.
type PlannerServiceClient interface {
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
}

type plannerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlannerServiceClient(cc grpc.ClientConnInterface) PlannerServiceClient {
	return &plannerServiceClient{cc}
}

func (c *plannerServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, PlannerService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plannerServiceClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, PlannerService_Plan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlannerServiceServer is the server API for PlannerService service.
// All implementations must embed UnimplementedPlannerServiceServer
// for forward compatibility.
//
// PlannerService is the Kapro Planner Interface (KPI).
//
// A planner plugin filters and orders eligible targets before Kapro binds
// ReleaseTarget objects. Kapro owns release state, retries, failure policy, and
// binding. Planner plugins only return planning decisions.
type PlannerServiceServer interface {
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	Plan(context.Context, *PlanRequest) (*PlanResponse, error)
	mustEmbedUnimplementedPlannerServiceServer()
}

// UnimplementedPlannerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlannerServiceServer struct{}

func (UnimplementedPlannerServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedPlannerServiceServer) Plan(context.Context, *PlanRequest) (*PlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedPlannerServiceServer) mustEmbedUnimplementedPlannerServiceServer() {}
func (UnimplementedPlannerServiceServer) testEmbeddedByValue()                        {}

// UnsafePlannerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlannerServiceServer will
// result in compilation errors.
type UnsafePlannerServiceServer interface {
	mustEmbedUnimplementedPlannerServiceServer()
}

func RegisterPlannerServiceServer(s grpc.ServiceRegistrar, srv PlannerServiceServer) {
	// If the following call panics, it indicates UnimplementedPlannerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlannerService_ServiceDesc, srv)
}

func _PlannerService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlannerServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlannerService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlannerServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlannerService_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlannerServiceServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlannerService_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlannerServiceServer).Plan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlannerService_ServiceDesc is the grpc.ServiceDesc for PlannerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlannerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kapro.kpi.v1alpha1.PlannerService",
	HandlerType: (*PlannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _PlannerService_GetCapabilities_Handler,
		},
		{
			MethodName: "Plan",
			Handler:    _PlannerService_Plan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spec/kpi/v1alpha1/planner.proto",
}
