apiVersion: kapro.io/v1alpha1
kind: Promotion
metadata:
  name: checkout-v1-2-3
  labels:
    app.kapro.io/name: checkout
    env.kapro.io/tier: prod
spec:
  sourceRef: checkout
  artifact:
    image: checkout-api
    tag: v1.2.3
    repository: oci://europe-west3-docker.pkg.dev/my-project/kapro-sources/checkout
    digest: sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  promotionPlans:
    - name: main
      promotionplan: checkout-progressive
  policies:
    - name: checkout-prod-guardrails
  suspended: false
  timeout: 4h
