// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: spec/kai/v1alpha1/actuator.proto

package kaiv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_spec_kai_v1alpha1_actuator_proto_rawDescGZIP(), []int{0}
}

type GetCapabilitiesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractVersion string                 `protobuf:"bytes,1,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	PluginVersion   string                 `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_spec_kai_v1alpha1_actuator_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapabilitiesResponse) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ApplyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Release         string                 `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Target          string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Pipeline        string                 `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Stage           string                 `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`
	Version         string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	PreviousVersion string                 `protobuf:"bytes,6,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	Parameters      map[string]string      `protobuf:"bytes,7,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_spec_kai_v1alpha1_actuator_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyRequest) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *ApplyRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ApplyRequest) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *ApplyRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ApplyRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApplyRequest) GetPreviousVersion() string {
	if x != nil {
		return x.PreviousVersion
	}
	return ""
}

func (x *ApplyRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_spec_kai_v1alpha1_actuator_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ApplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IsConvergedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       string                 `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConvergedRequest) Reset() {
	*x = IsConvergedRequest{}
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConvergedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConvergedRequest) ProtoMessage() {}

func (x *IsConvergedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConvergedRequest.ProtoReflect.Descriptor instead.
func (*IsConvergedRequest) Descriptor() ([]byte, []int) {
	return file_spec_kai_v1alpha1_actuator_proto_rawDescGZIP(), []int{4}
}

func (x *IsConvergedRequest) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *IsConvergedRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *IsConvergedRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *IsConvergedRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type IsConvergedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Converged     bool                   `protobuf:"varint,1,opt,name=converged,proto3" json:"converged,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsConvergedResponse) Reset() {
	*x = IsConvergedResponse{}
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsConvergedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsConvergedResponse) ProtoMessage() {}

func (x *IsConvergedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsConvergedResponse.ProtoReflect.Descriptor instead.
func (*IsConvergedResponse) Descriptor() ([]byte, []int) {
	return file_spec_kai_v1alpha1_actuator_proto_rawDescGZIP(), []int{5}
}

func (x *IsConvergedResponse) GetConverged() bool {
	if x != nil {
		return x.Converged
	}
	return false
}

func (x *IsConvergedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RollbackRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Release         string                 `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Target          string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	PreviousVersion string                 `protobuf:"bytes,4,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	Parameters      map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_spec_kai_v1alpha1_actuator_proto_rawDescGZIP(), []int{6}
}

func (x *RollbackRequest) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *RollbackRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RollbackRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RollbackRequest) GetPreviousVersion() string {
	if x != nil {
		return x.PreviousVersion
	}
	return ""
}

func (x *RollbackRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_kai_v1alpha1_actuator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_spec_kai_v1alpha1_actuator_proto_rawDescGZIP(), []int{7}
}

func (x *RollbackResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RollbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_spec_kai_v1alpha1_actuator_proto protoreflect.FileDescriptor

const file_spec_kai_v1alpha1_actuator_proto_rawDesc = "" +
	"\n" +
	" spec/kai/v1alpha1/actuator.proto\x12\x12kapro.kai.v1alpha1\"\x18\n" +
	"\x16GetCapabilitiesRequest\"\x8f\x01\n" +
	"\x17GetCapabilitiesResponse\x12)\n" +
	"\x10contract_version\x18\x01 \x01(\tR\x0fcontractVersion\x12%\n" +
	"\x0eplugin_version\x18\x02 \x01(\tR\rpluginVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\xc8\x02\n" +
	"\fApplyRequest\x12\x18\n" +
	"\arelease\x18\x01 \x01(\tR\arelease\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1a\n" +
	"\bpipeline\x18\x03 \x01(\tR\bpipeline\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12)\n" +
	"\x10previous_version\x18\x06 \x01(\tR\x0fpreviousVersion\x12P\n" +
	"\n" +
	"parameters\x18\a \x03(\v20.kapro.kai.v1alpha1.ApplyRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\rApplyResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf7\x01\n" +
	"\x12IsConvergedRequest\x12\x18\n" +
	"\arelease\x18\x01 \x01(\tR\arelease\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12V\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v26.kapro.kai.v1alpha1.IsConvergedRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x13IsConvergedResponse\x12\x1c\n" +
	"\tconverged\x18\x01 \x01(\bR\tconverged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9c\x02\n" +
	"\x0fRollbackRequest\x12\x18\n" +
	"\arelease\x18\x01 \x01(\tR\arelease\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12)\n" +
	"\x10previous_version\x18\x04 \x01(\tR\x0fpreviousVersion\x12S\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v23.kapro.kai.v1alpha1.RollbackRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x10RollbackResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x82\x03\n" +
	"\x0fActuatorService\x12j\n" +
	"\x0fGetCapabilities\x12*.kapro.kai.v1alpha1.GetCapabilitiesRequest\x1a+.kapro.kai.v1alpha1.GetCapabilitiesResponse\x12L\n" +
	"\x05Apply\x12 .kapro.kai.v1alpha1.ApplyRequest\x1a!.kapro.kai.v1alpha1.ApplyResponse\x12^\n" +
	"\vIsConverged\x12&.kapro.kai.v1alpha1.IsConvergedRequest\x1a'.kapro.kai.v1alpha1.IsConvergedResponse\x12U\n" +
	"\bRollback\x12#.kapro.kai.v1alpha1.RollbackRequest\x1a$.kapro.kai.v1alpha1.RollbackResponseB.Z,kapro.io/kapro/spec/kai/v1alpha1;kaiv1alpha1b\x06proto3"

var (
	file_spec_kai_v1alpha1_actuator_proto_rawDescOnce sync.Once
	file_spec_kai_v1alpha1_actuator_proto_rawDescData []byte
)

func file_spec_kai_v1alpha1_actuator_proto_rawDescGZIP() []byte {
	file_spec_kai_v1alpha1_actuator_proto_rawDescOnce.Do(func() {
		file_spec_kai_v1alpha1_actuator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_kai_v1alpha1_actuator_proto_rawDesc), len(file_spec_kai_v1alpha1_actuator_proto_rawDesc)))
	})
	return file_spec_kai_v1alpha1_actuator_proto_rawDescData
}

var file_spec_kai_v1alpha1_actuator_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_spec_kai_v1alpha1_actuator_proto_goTypes = []any{
	(*GetCapabilitiesRequest)(nil),  // 0: kapro.kai.v1alpha1.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil), // 1: kapro.kai.v1alpha1.GetCapabilitiesResponse
	(*ApplyRequest)(nil),            // 2: kapro.kai.v1alpha1.ApplyRequest
	(*ApplyResponse)(nil),           // 3: kapro.kai.v1alpha1.ApplyResponse
	(*IsConvergedRequest)(nil),      // 4: kapro.kai.v1alpha1.IsConvergedRequest
	(*IsConvergedResponse)(nil),     // 5: kapro.kai.v1alpha1.IsConvergedResponse
	(*RollbackRequest)(nil),         // 6: kapro.kai.v1alpha1.RollbackRequest
	(*RollbackResponse)(nil),        // 7: kapro.kai.v1alpha1.RollbackResponse
	nil,                             // 8: kapro.kai.v1alpha1.ApplyRequest.ParametersEntry
	nil,                             // 9: kapro.kai.v1alpha1.IsConvergedRequest.ParametersEntry
	nil,                             // 10: kapro.kai.v1alpha1.RollbackRequest.ParametersEntry
}
var file_spec_kai_v1alpha1_actuator_proto_depIdxs = []int32{
	8,  // 0: kapro.kai.v1alpha1.ApplyRequest.parameters:type_name -> kapro.kai.v1alpha1.ApplyRequest.ParametersEntry
	9,  // 1: kapro.kai.v1alpha1.IsConvergedRequest.parameters:type_name -> kapro.kai.v1alpha1.IsConvergedRequest.ParametersEntry
	10, // 2: kapro.kai.v1alpha1.RollbackRequest.parameters:type_name -> kapro.kai.v1alpha1.RollbackRequest.ParametersEntry
	0,  // 3: kapro.kai.v1alpha1.ActuatorService.GetCapabilities:input_type -> kapro.kai.v1alpha1.GetCapabilitiesRequest
	2,  // 4: kapro.kai.v1alpha1.ActuatorService.Apply:input_type -> kapro.kai.v1alpha1.ApplyRequest
	4,  // 5: kapro.kai.v1alpha1.ActuatorService.IsConverged:input_type -> kapro.kai.v1alpha1.IsConvergedRequest
	6,  // 6: kapro.kai.v1alpha1.ActuatorService.Rollback:input_type -> kapro.kai.v1alpha1.RollbackRequest
	1,  // 7: kapro.kai.v1alpha1.ActuatorService.GetCapabilities:output_type -> kapro.kai.v1alpha1.GetCapabilitiesResponse
	3,  // 8: kapro.kai.v1alpha1.ActuatorService.Apply:output_type -> kapro.kai.v1alpha1.ApplyResponse
	5,  // 9: kapro.kai.v1alpha1.ActuatorService.IsConverged:output_type -> kapro.kai.v1alpha1.IsConvergedResponse
	7,  // 10: kapro.kai.v1alpha1.ActuatorService.Rollback:output_type -> kapro.kai.v1alpha1.RollbackResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_spec_kai_v1alpha1_actuator_proto_init() }
func file_spec_kai_v1alpha1_actuator_proto_init() {
	if File_spec_kai_v1alpha1_actuator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_kai_v1alpha1_actuator_proto_rawDesc), len(file_spec_kai_v1alpha1_actuator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spec_kai_v1alpha1_actuator_proto_goTypes,
		DependencyIndexes: file_spec_kai_v1alpha1_actuator_proto_depIdxs,
		MessageInfos:      file_spec_kai_v1alpha1_actuator_proto_msgTypes,
	}.Build()
	File_spec_kai_v1alpha1_actuator_proto = out.File
	file_spec_kai_v1alpha1_actuator_proto_goTypes = nil
	file_spec_kai_v1alpha1_actuator_proto_depIdxs = nil
}
