---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kapro-operator.fullname" . }}-manager-role
  labels:
    {{- include "kapro-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluxcd.controlplane.io
  resources:
  - resourcesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - approvals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - approvals/status
  - kaproes/status
  - memberclusters/status
  - pluginregistrations/status
  - releases/status
  - releasetargets/status
  - releasetriggers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kapro.io
  resources:
  - kaproapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - kaproes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - memberclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - agentpolicies
  - pluginregistrations
  - releasetriggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kapro.io
  resources:
  - agentpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kapro.io
  resources:
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kapro.io
  resources:
  - releases/finalizers
  verbs:
  - update
- apiGroups:
  - kapro.io
  resources:
  - releasetargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kapro-operator.fullname" . }}-manager-role-binding
  labels:
    {{- include "kapro-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kapro-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "kapro-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
