// Package v1alpha1 contains the Kapro API types.
//
// API group: kapro.io
// Version:   v1alpha1
//
// Primary user-authored CRDs (KISS path):
//   - Kapro          — fleet entry point: source, delivery, clusters, plan
//   - Promotion      — durable rollout intent; usually created via `kapro promote`
//   - Approval       — human gate signal to unblock one target-cluster rollout or stage
//
// Optional/advanced user-authored CRDs:
//   - PromotionPlan  — reusable promotion template composed of ordered stages,
//                      referenced from Promotion.spec.promotionPlans (override)
//                      or Kapro.spec.promotionplan (inline default).
//   - PromotionSource — reusable promotion unit catalog (shared across Kapro objects)
//   - PromotionTrigger — safe-by-default autonomous Promotion creation from verified artifacts
//   - PluginRegistration — external actuator, gate, and planner plugin registration
//   - AgentPolicy    — AI trust boundary and audit policy
//   - FleetClusterTemplate — fleet auto-import template (ApplicationSet-shaped);
//                            the controller generates FleetCluster objects from it.
//   - BackendProfile — delivery backend configuration referenced by Kapro.spec.delivery.backendRef.
//
// Controller-managed runtime (observe; do not author directly):
//   - PromotionRun    — one execution attempt of a Promotion; the PromotionController
//                       creates it. Mirrors Deployment→ReplicaSet→Pod and Service→Task.
//   - PromotionTarget — one target-cluster execution; owned by a PromotionRun
//   - FleetCluster    — fleet inventory and observed cluster state reported to the hub
//                       (generated by FleetClusterTemplate or written by the hub
//                       bootstrap when hand-imported)
//
// Authoring path:
//   user → Kapro (one-time fleet setup) + Promotion (per-rollout intent)
// Runtime path:
//   PromotionController → PromotionRun → PromotionTarget(s) → spoke backend
//
// `kapro promotionrun create` exists as an advanced/debug escape hatch but
// the supported path is `kapro promote` (or applying a Promotion manifest).
//
// API maturity, deprecation, schema compatibility, and upgrade expectations are
// documented in docs/api-stability.md.
//
// +kubebuilder:object:generate=true
// +groupName=kapro.io
package v1alpha1
