// Package v1alpha1 contains the Kapro API types.
//
// API group: kapro.io
// Version:   v1alpha1
//
// Primary user-authored CRDs (KISS path):
//   - Kapro          — fleet entry point: source, delivery, clusters, plan
//   - PromotionRun   — promotion intent; usually created via `kapro promote`
//   - Approval       — human gate signal to unblock one target-cluster rollout or stage
//
// Optional/advanced user-authored CRDs:
//   - PromotionPlan  — reusable promotion template composed of ordered stages,
//                      referenced from PromotionRun.spec.promotionplans. Distinct
//                      from Kapro.spec.promotionplan, which is an inline
//                      single-fleet plan for the KISS path.
//   - PromotionSource — reusable promotion unit catalog (shared across Kapro objects)
//   - PromotionTrigger — safe-by-default autonomous PromotionRun creation from verified artifacts
//   - PluginRegistration — external actuator, gate, and planner plugin registration
//   - AgentPolicy    — AI trust boundary and audit policy
//   - FleetClusterTemplate — fleet auto-import template (ApplicationSet-shaped);
//                            the controller generates FleetCluster objects from it.
//   - BackendProfile — delivery backend configuration referenced by Kapro.spec.delivery.backendRef.
//
// Controller-managed (observe; do not author directly):
//   - PromotionTarget — one target-cluster execution; owned by a PromotionRun
//   - FleetCluster   — fleet inventory and observed cluster state reported to the hub
//                      (generated by FleetClusterTemplate or written by the hub
//                      bootstrap when hand-imported)
//
// PromotionRuns are created by the CLI (`kapro promote`), users applying
// PromotionRun manifests directly, or PromotionTriggers. The Kapro controller
// does not generate PromotionRuns from spec changes on the Kapro object.
//
// API maturity, deprecation, schema compatibility, and upgrade expectations are
// documented in docs/api-stability.md.
//
// +kubebuilder:object:generate=true
// +groupName=kapro.io
package v1alpha1
