// Kapro CRD: the single fleet entry point that ties source units, a delivery
// profile, clusters, and a promotion plan together.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ---- Kapro ------------------------------------------------------------------

// KaproSpec defines the desired state of a Kapro fleet.
type KaproSpec struct {
	// Registry is the OCI registry URL for generated pull-mode artifacts.
	// Native Argo/Flux sources may omit it when no Kapro-packaged artifact is used.
	// +optional
	Registry KaproRegistry `json:"registry,omitempty"`
	// SourceRef is the optional name of a separate PromotionSource that defines
	// units to deploy. Use Source for the KISS single-object path; use SourceRef
	// when teams want to share a source catalog across multiple Kapro objects.
	// +optional
	SourceRef string `json:"sourceRef,omitempty"`
	// Source defines deployable units inline for the KISS single-object path.
	// If SourceRef is set, SourceRef wins.
	// +optional
	Source *PromotionSourceSpec `json:"source,omitempty"`
	// Delivery selects the backend-neutral fleet delivery profile.
	Delivery DeliverySpec `json:"delivery"`
	// Clusters defines the target clusters in the fleet.
	// +kubebuilder:validation:MinItems=1
	Clusters []KaproCluster `json:"clusters"`
	// PromotionPlan defines the progressive delivery stages.
	PromotionPlan KaproPromotionPlan `json:"promotionplan"`
	// Suspended pauses Kapro reconciliation.
	// +kubebuilder:default=false
	Suspended bool `json:"suspended,omitempty"`
}

// KaproRegistry configures the OCI registry used by FluxInstance on spokes.
type KaproRegistry struct {
	// URL is the OCI registry URL (e.g. oci://europe-west1-docker.pkg.dev/project/repo)
	URL string `json:"url"`
	// Provider is the auth provider (generic, gcp, aws, azure).
	// +kubebuilder:default="generic"
	Provider string `json:"provider,omitempty"`
	// SecretRef references a Secret for registry auth (pushed to spokes).
	// +optional
	SecretRef string `json:"secretRef,omitempty"`
}

// KaproCluster defines a spoke cluster in the fleet.
type KaproCluster struct {
	// Name is the cluster identifier.
	Name string `json:"name"`
	// Labels for stage selection.
	Labels map[string]string `json:"labels"`
	// Provider is "kubeconfig" (default), "gcp", or "gcp-fleet".
	// gcp-fleet uses Fleet API for discovery + WI auth via gke-gcloud-auth-plugin.
	// +kubebuilder:validation:Enum=kubeconfig;gcp;gcp-fleet
	// +kubebuilder:default="kubeconfig"
	Provider string `json:"provider,omitempty"`
	// KubeconfigSecret references the kubeconfig Secret name (provider=kubeconfig).
	// For gcp/gcp-fleet providers, this is auto-generated by the controller.
	// +optional
	KubeconfigSecret string `json:"kubeconfigSecret,omitempty"`
	// GCP config (provider=gcp or gcp-fleet).
	// +optional
	GCP *KaproClusterGCP `json:"gcp,omitempty"`
}

// KaproClusterGCP holds GCP-specific cluster config.
type KaproClusterGCP struct {
	// Project is the GCP project ID containing the spoke cluster.
	Project string `json:"project"`
	// ClusterName is the GKE cluster name (for gcp provider).
	// For gcp-fleet, this is resolved from Fleet membership.
	// +optional
	ClusterName string `json:"clusterName,omitempty"`
	// Region is the GKE cluster location (zone or region).
	// +optional
	Region string `json:"region,omitempty"`
}

// KaproPromotionPlan defines the progressive delivery stages.
type KaproPromotionPlan struct {
	// Stages defines the progressive delivery wave ordering.
	Stages []KaproStage `json:"stages"`
}

// KaproStage is one wave in the delivery promotionplan.
type KaproStage struct {
	// Name of the stage.
	Name string `json:"name"`
	// Selector matches clusters by labels.
	Selector map[string]string `json:"selector"`
	// DependsOn declares upstream stage dependencies.
	// +optional
	DependsOn []StageDependency `json:"dependsOn,omitempty"`
	// Gate defines approval/soak/metrics requirements for this stage.
	// +optional
	Gate *GatePolicySpec `json:"gate,omitempty"`
}

// KaproStatus defines the observed state of Kapro.
type KaproStatus struct {
	ObservedGeneration int64              `json:"observedGeneration,omitempty"`
	Conditions         []metav1.Condition `json:"conditions,omitempty"`
	// ClusterCount is the number of clusters in the fleet.
	ClusterCount int32 `json:"clusterCount,omitempty"`
	// ConvergedCount is the number of clusters where all HelmReleases are Ready.
	ConvergedCount int32 `json:"convergedCount,omitempty"`
	// UnitCount is the number of units from the resolved PromotionSource.
	UnitCount int32 `json:"unitCount,omitempty"`
	// Version is the current primary unit version being deployed.
	// +optional
	Version string `json:"version,omitempty"`
	// Inventory lists the generated spoke resources (FluxInstance, OCIRepository names).
	// +optional
	Inventory []string `json:"inventory,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=kp,categories=kapro-all
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].status`
// +kubebuilder:printcolumn:name="SourceRef",type=string,JSONPath=`.spec.sourceRef`
// +kubebuilder:printcolumn:name="Clusters",type=integer,JSONPath=`.status.clusterCount`
// +kubebuilder:printcolumn:name="Converged",type=integer,JSONPath=`.status.convergedCount`
// +kubebuilder:printcolumn:name="Version",type=string,JSONPath=`.status.version`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// Kapro is the single entry point for fleet delivery. Users define or reference
// source units, select a backend profile, and define clusters and promotion
// stages. Backend adapters own Flux, Argo, or other delivery-system details.
type Kapro struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              KaproSpec   `json:"spec,omitempty"`
	Status            KaproStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type KaproList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Kapro `json:"items"`
}
