// Code generated by controller-gen. DO NOT EDIT.

// This file is a placeholder. Run `make generate` to regenerate:
//   make generate
//
// controller-gen generates DeepCopy methods for all CRD types.
// Until then, stub implementations are provided here to allow compilation.

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

// DeepCopyObject stubs — replace with generated code via `make generate`

func (in *Artifact) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *Artifact) DeepCopy() *Artifact {
	if in == nil {
		return nil
	}
	out := new(Artifact)
	*out = *in
	return out
}

func (in *ArtifactList) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *ArtifactList) DeepCopy() *ArtifactList {
	if in == nil {
		return nil
	}
	out := new(ArtifactList)
	*out = *in
	return out
}

func (in *Environment) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *Environment) DeepCopy() *Environment {
	if in == nil {
		return nil
	}
	out := new(Environment)
	*out = *in
	return out
}

func (in *EnvironmentList) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *EnvironmentList) DeepCopy() *EnvironmentList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentList)
	*out = *in
	return out
}

func (in *ClusterRegistration) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *ClusterRegistration) DeepCopy() *ClusterRegistration {
	if in == nil {
		return nil
	}
	out := new(ClusterRegistration)
	*out = *in
	return out
}

func (in *ClusterRegistrationList) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *ClusterRegistrationList) DeepCopy() *ClusterRegistrationList {
	if in == nil {
		return nil
	}
	out := new(ClusterRegistrationList)
	*out = *in
	return out
}

func (in *PromotionPolicy) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *PromotionPolicy) DeepCopy() *PromotionPolicy {
	if in == nil {
		return nil
	}
	out := new(PromotionPolicy)
	*out = *in
	return out
}

func (in *PromotionPolicyList) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *PromotionPolicyList) DeepCopy() *PromotionPolicyList {
	if in == nil {
		return nil
	}
	out := new(PromotionPolicyList)
	*out = *in
	return out
}

func (in *Pipeline) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *Pipeline) DeepCopy() *Pipeline {
	if in == nil {
		return nil
	}
	out := new(Pipeline)
	*out = *in
	return out
}

func (in *PipelineList) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *PipelineList) DeepCopy() *PipelineList {
	if in == nil {
		return nil
	}
	out := new(PipelineList)
	*out = *in
	return out
}

func (in *Release) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *Release) DeepCopy() *Release {
	if in == nil {
		return nil
	}
	out := new(Release)
	*out = *in
	return out
}

func (in *ReleaseList) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *ReleaseList) DeepCopy() *ReleaseList {
	if in == nil {
		return nil
	}
	out := new(ReleaseList)
	*out = *in
	return out
}

func (in *Approval) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *Approval) DeepCopy() *Approval {
	if in == nil {
		return nil
	}
	out := new(Approval)
	*out = *in
	return out
}

func (in *ApprovalList) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *ApprovalList) DeepCopy() *ApprovalList {
	if in == nil {
		return nil
	}
	out := new(ApprovalList)
	*out = *in
	return out
}

func (in *Promotion) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *Promotion) DeepCopy() *Promotion {
	if in == nil {
		return nil
	}
	out := new(Promotion)
	*out = *in
	return out
}

func (in *PromotionList) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *PromotionList) DeepCopy() *PromotionList {
	if in == nil {
		return nil
	}
	out := new(PromotionList)
	*out = *in
	return out
}

func (in *BatchRun) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *BatchRun) DeepCopy() *BatchRun {
	if in == nil {
		return nil
	}
	out := new(BatchRun)
	*out = *in
	return out
}

func (in *BatchRunList) DeepCopyObject() runtime.Object {
	out := in.DeepCopy()
	return out
}
func (in *BatchRunList) DeepCopy() *BatchRunList {
	if in == nil {
		return nil
	}
	out := new(BatchRunList)
	*out = *in
	return out
}
