apiVersion: kapro.io/v1alpha1
kind: MemberCluster
metadata:
  name: prod-eu
  labels:
    kapro.io/tier: production
    kapro.io/region: europe-west3
    kapro.io/country: de
spec:
  delivery:
    mode: pull
    backendRef: flux
    parameters:
      ociRepository: app-bundle
      namespace: flux-system
