apiVersion: kapro.io/v1alpha1
kind: Promotion
metadata:
  name: hello-world-0-3-1
  labels:
    kapro.io/unit: hello-world
    kapro.io/team: tutorial
spec:
  deliveryUnitRef: hello-world
  fleetRef: hello-world
  planRef: hello-world
  versions:
    web: 0.3.1
    worker: 0.3.1
  timeout: 30m
