// Package v1alpha1 contains the Fleet API types.
//
// API group: kapro.io
// Version:   v1alpha1
//
// Primary user-authored CRDs (KISS path):
//   - DeliveryUnit   — app/workload delivery identity, source shape, trigger intent
//   - Fleet          — target set and delivery defaults
//   - Plan           — reusable rollout strategy composed of ordered stages
//   - Promotion      — explicit rollout action; usually created via `kapro promote`
//   - Approval       — human gate signal to unblock one target-cluster rollout or stage
//
// Optional/advanced user-authored CRDs:
//   - Plugin — external actuator, gate, and planner plugin registration
//   - Policy    — AI trust boundary and audit policy
//   - ClusterTemplate — fleet auto-import template (ApplicationSet-shaped);
//     the controller generates Cluster objects from it.
//   - Cluster — fleet inventory and observed cluster state reported to the hub
//     (generated by ClusterTemplate or authored by platform teams).
//   - Substrate — delivery substrate configuration referenced by Fleet.spec.delivery.ref.
//   - SubstrateClass — delivery substrate class and typed config contract.
//
// Controller-derived user-group CRDs are visible for inspection but normally
// written by Kapro from DeliveryUnit:
//   - Source  — derived from DeliveryUnit.spec.source
//   - Trigger — derived from DeliveryUnit.spec.triggers[]
//
// Controller-managed runtime objects live in runtime.kapro.io/v1alpha1.
// Observe them; do not author them directly:
//   - PromotionRun — one execution attempt of a Promotion.
//   - Target       — one target-cluster execution owned by a PromotionRun.
//   - DecisionTrace — signed controller decision evidence.
//
// Authoring path:
//
//	user → DeliveryUnit + Fleet + Plan (setup) + Promotion (rollout action)
//
// Runtime path:
//
//	PromotionController → PromotionRun → Target(s) → spoke substrate
//
// `kapro promotionrun create` exists as an advanced/debug escape hatch but
// the supported path is `kapro promote` (or applying a Promotion manifest).
//
// API maturity, deprecation, schema compatibility, and upgrade expectations are
// documented in docs/api-stability.md.
//
// +kubebuilder:object:generate=true
// +groupName=kapro.io
package v1alpha1
