// Fleet CRD: target set and delivery defaults for one group of clusters.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ---- Fleet ------------------------------------------------------------------

// FleetSpec defines delivery defaults and target clusters for one fleet.
type FleetSpec struct {
	// Registry is the OCI registry URL for generated pull-mode artifacts.
	// Native Argo/Flux sources may omit it when no Fleet-packaged artifact is used.
	// +optional
	Registry KaproRegistry `json:"registry,omitempty"`
	// SourceRef is a compatibility hook for legacy Fleet-packaged workflows.
	// The public-preview authoring path puts source intent on DeliveryUnit and
	// lets Kapro derive Source objects from that layer.
	// +optional
	SourceRef string `json:"sourceRef,omitempty"`
	// Source is a compatibility hook for legacy single-object packaging
	// workflows. New manifests should use DeliveryUnit.spec.source instead.
	// +optional
	Source *SourceSpec `json:"source,omitempty"`
	// Delivery selects the substrate-neutral delivery defaults copied to
	// generated Cluster objects.
	Delivery DeliverySpec `json:"delivery"`
	// Clusters defines the target clusters in the fleet.
	// +kubebuilder:validation:MinItems=1
	Clusters []ClusterRef `json:"clusters"`
	// Plan is a compatibility hook for legacy inline rollout stages. New
	// manifests should use a standalone Plan and reference it from Promotion or
	// DeliveryUnit defaults.
	// +optional
	Plan KaproPlan `json:"plan,omitempty"`
	// Suspended pauses Fleet reconciliation.
	// +kubebuilder:default=false
	Suspended bool `json:"suspended,omitempty"`
}

// KaproRegistry configures the OCI registry used by FluxInstance on spokes.
type KaproRegistry struct {
	// URL is the OCI registry URL (e.g. oci://europe-west1-docker.pkg.dev/project/repo)
	URL string `json:"url"`
	// Provider is the auth provider (generic, gcp, aws, azure).
	// +kubebuilder:default="generic"
	Provider string `json:"provider,omitempty"`
	// SecretRef references a Secret for registry auth (pushed to spokes).
	// +optional
	SecretRef string `json:"secretRef,omitempty"`
}

// ClusterRef defines a spoke cluster in the fleet.
type ClusterRef struct {
	// Name is the cluster identifier.
	Name string `json:"name"`
	// Labels for stage selection.
	Labels map[string]string `json:"labels"`
	// Provider is "kubeconfig" (default), "gcp", or "gcp-fleet".
	// gcp-fleet uses Fleet API for discovery + WI auth via gke-gcloud-auth-plugin.
	// +kubebuilder:validation:Enum=kubeconfig;gcp;gcp-fleet
	// +kubebuilder:default="kubeconfig"
	Provider string `json:"provider,omitempty"`
	// KubeconfigSecret references the kubeconfig Secret name (provider=kubeconfig).
	// For gcp/gcp-fleet providers, this is auto-generated by the controller.
	// +optional
	KubeconfigSecret string `json:"kubeconfigSecret,omitempty"`
	// GCP config (provider=gcp or gcp-fleet).
	// +optional
	GCP *ClusterGCP `json:"gcp,omitempty"`
}

// ClusterGCP holds GCP-specific cluster config.
type ClusterGCP struct {
	// Project is the GCP project ID containing the spoke cluster.
	Project string `json:"project"`
	// ClusterName is the GKE cluster name (for gcp provider).
	// For gcp-fleet, this is resolved from Fleet membership.
	// +optional
	ClusterName string `json:"clusterName,omitempty"`
	// Region is the GKE cluster location (zone or region).
	// +optional
	Region string `json:"region,omitempty"`
}

// KaproPlan defines progressive delivery stages inline on a single Fleet
// object for compatibility. Prefer standalone Plan CRDs for new manifests.
type KaproPlan struct {
	// Stages defines the progressive delivery wave ordering.
	Stages []StageSpec `json:"stages"`
}

// StageSpec is one wave in the delivery plan.
type StageSpec struct {
	// Name of the stage.
	Name string `json:"name"`
	// Selector is a simple label map that matches clusters by labels. Standalone
	// Plan resources use Kubernetes LabelSelector syntax instead.
	Selector map[string]string `json:"selector"`
	// DependsOn declares upstream stage dependencies.
	// +optional
	DependsOn []StageDependency `json:"dependsOn,omitempty"`
	// Gate defines approval/soak/metrics requirements for this stage.
	// +optional
	Gate *GatePolicySpec `json:"gate,omitempty"`
}

// FleetStatus defines the observed state of Fleet.
type FleetStatus struct {
	ObservedGeneration int64              `json:"observedGeneration,omitempty"`
	Conditions         []metav1.Condition `json:"conditions,omitempty"`
	// ClusterCount is the number of clusters in the fleet.
	ClusterCount int32 `json:"clusterCount,omitempty"`
	// ConvergedCount is the number of clusters where all HelmReleases are Ready.
	ConvergedCount int32 `json:"convergedCount,omitempty"`
	// UnitCount is the number of units from the resolved Source.
	UnitCount int32 `json:"unitCount,omitempty"`
	// Version is the current primary unit version being deployed.
	// +optional
	Version string `json:"version,omitempty"`
	// Inventory lists the generated spoke resources (FluxInstance, OCIRepository names).
	// +optional
	Inventory []string `json:"inventory,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=flt,categories=kapro-all
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].status`
// +kubebuilder:printcolumn:name="Units",type=integer,JSONPath=`.status.unitCount`
// +kubebuilder:printcolumn:name="Clusters",type=integer,JSONPath=`.status.clusterCount`
// +kubebuilder:printcolumn:name="Converged",type=integer,JSONPath=`.status.convergedCount`
// +kubebuilder:printcolumn:name="Version",type=string,JSONPath=`.status.version`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// Fleet is the target-set entry point for fleet delivery. Users select delivery
// defaults and define clusters. DeliveryUnit owns source shape, Plan owns
// rollout strategy, and Promotion remains the explicit action boundary.
type Fleet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FleetSpec   `json:"spec,omitempty"`
	Status            FleetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type FleetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Fleet `json:"items"`
}
