resources:
- bases/kapro.io_approvals.yaml
- bases/kapro.io_backends.yaml
- bases/kapro.io_clusters.yaml
- bases/kapro.io_clustertemplates.yaml
- bases/kapro.io_fleets.yaml
- bases/kapro.io_plans.yaml
- bases/kapro.io_plugins.yaml
- bases/kapro.io_policies.yaml
- bases/kapro.io_promotionruns.yaml
- bases/kapro.io_promotions.yaml
- bases/kapro.io_sources.yaml
- bases/kapro.io_targets.yaml
- bases/kapro.io_triggers.yaml
