resources:
- bases/argocd.substrate.kapro.io_argocdsubstrateconfigs.yaml
- bases/flux.substrate.kapro.io_fluxsubstrateconfigs.yaml
- bases/kapro.io_adapterpolicies.yaml
- bases/kapro.io_approvals.yaml
- bases/kapro.io_clusters.yaml
- bases/kapro.io_clustertemplates.yaml
- bases/kapro.io_fleets.yaml
- bases/kapro.io_plans.yaml
- bases/kapro.io_plugins.yaml
- bases/kapro.io_policies.yaml
- bases/kapro.io_promotions.yaml
- bases/kapro.io_sources.yaml
- bases/kapro.io_substrateclasses.yaml
- bases/kapro.io_substrates.yaml
- bases/kapro.io_triggers.yaml
- bases/kubernetes.substrate.kapro.io_kubernetesapplyconfigs.yaml
- bases/oci.substrate.kapro.io_ocibundleapplyconfigs.yaml
- bases/runtime.kapro.io_decisiontraces.yaml
- bases/runtime.kapro.io_promotionruns.yaml
- bases/runtime.kapro.io_targets.yaml
