resources:
- bases/kapro.io_agentpolicies.yaml
- bases/kapro.io_approvals.yaml
- bases/kapro.io_promotionsources.yaml
- bases/kapro.io_kaproes.yaml
- bases/kapro.io_fleetclusters.yaml
- bases/kapro.io_fleetclustertemplates.yaml
- bases/kapro.io_promotionplans.yaml
- bases/kapro.io_pluginregistrations.yaml
- bases/kapro.io_promotionruns.yaml
- bases/kapro.io_promotiontargets.yaml
- bases/kapro.io_promotiontriggers.yaml
