apiVersion: kapro.io/v1alpha1
kind: BackendProfile
metadata:
  name: flux-observe
spec:
  driver: flux
  runtime: Hub
  parameters:
    namespace: flux-system
  discovery:
    enabled: true
    managementPolicy: Observe
    selector:
      matchLabels:
        kapro.io/import: "true"
