apiVersion: kapro.io/v1alpha1
kind: Promotion
metadata:
  name: hello-world-0-1-1
  labels:
    kapro.io/unit: hello-world
    kapro.io/team: tutorial
spec:
  deliveryUnitRef: hello-world
  fleetRef: hello-world
  planRef: hello-world
  version: 0.1.1
  timeout: 30m
