apiVersion: v1
kind: Service
metadata:
  name: checkout-direct
  namespace: default
  labels:
    app.kubernetes.io/name: checkout-direct
spec:
  selector:
    app.kubernetes.io/name: checkout-direct
  ports:
    - name: http
      port: 80
      targetPort: 8080
